---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: all
  remote_user: dpdk
  roles:
    - common
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: setup ring env
  hosts: ring 
  remote_user: dpdk
  roles:
    - ring
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: setup vhost env
  hosts: vhost 
  remote_user: dpdk
  roles:
    - vhost
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
