---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: all
  remote_user: {{ remote_user }} 
  roles:
    - common

- name: setup ring env
  hosts: ring 
  remote_user: {{ remote_user }}
  roles:
    - ring

- name: setup vhost env
  hosts: vhost 
  remote_user: {{ remote_user }}
  roles:
    - vhost
