---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: all
  remote_user: dpdk
  vars:
    nr_hugepages: 2048
    uname_r: 4.4.0-22-generic
    install_dir: "{{ ansible_env.HOME }}/dpdk-home"
    spp_dir: "{{ install_dir }}/spp"
    dpdk_target: x86_64-ivshmem-linuxapp-gcc
  roles:
    - common
