syntax on
set shiftwidth=2
set tabstop=2
set expandtab
set number
set showcmd
set showmatch
set hlsearch
set laststatus=2
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8
set autoindent

set visualbell t_vb=
set noerrorbells

"colorscheme darkblue

" Cancel auto comment out.
autocmd FileType * setlocal formatoptions-=ro

filetype on
filetype indent on
filetype plugin on

" quickrunの設定
let g:quickrun_config = {}
let g:quickrun_config.processing = {
  \ 'command': 'processing-java',
  \ 'exec': '%c --sketch=$PWD/ --output=./Documents/Processing/output --run --force',
  \ }

" NeoBundleの設定
if !1 | finish | endif

if has('vim_starting')
  if &compatible
    set nocompatible
  endif

  " Required
	set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

" After install, turn shell =/.vim/bundle/vimproc, (n,g)make -f makefile.
NeoBundle 'Shougo/vimproc'

NeoBundle 'quickrun.vim'
NeoBundle 'thinca/vim-ref'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimfiler'
"NeoBundle 'JavaScript-syntax'
"NeoBundle 'pangloss/vim-javascript'
NeoBundle 'nathanaelkane/vim-indent-guides'

NeoBundle 'kien/rainbow_parentheses.vim'
NeoBundle 'tpope/vim-fireplace'
NeoBundle 'tpope/vim-classpath'
NeoBundle 'tpope/vim-rsi'
NeoBundle 'tpope/vim-endwise'
"NeoBundle 'jnwhiteh/vim-golang'

call neobundle#end()

" Required
filetype plugin indent on 

NeoBundleCheck

autocmd Filetype * set formatoptions-=ro

" vim-instant-markdownの設定
"let g:instant_markdown_slow = 1
