syntax on
set shiftwidth=2
set tabstop=2
set expandtab
set number
set showcmd
set showmatch
set hlsearch
set laststatus=2
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8
set autoindent

set visualbell t_vb=
set noerrorbells

"colorscheme darkblue

" Cancel auto comment out.
autocmd FileType * setlocal formatoptions-=ro

filetype on
filetype indent on
filetype plugin on
