---
#- name: set hugepages size
#  become: yes
#  command: sh -c "echo {{ nr_hugepages }} > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"

#- name: fstab
#  replace:
#    dest=/etc/fstab
#    regexp='nodev /mnt/huge hugetlbfs *$'
#    replace='nodev /mnt/huge hugetlbfs defaults 0 0'

- name: clean grub hugepage opt
  replace:
    dest=/etc/default/grub
    regexp='(hugepages=\d+ |default_hugepagesz=1G |hugepagesz=1G |hugepagesz=2M )'
    replace=''
  become: yes

- name: set grub hugepage 2MB
  when: hugepage_size == "2M"
  replace:
    dest=/etc/default/grub
    regexp='^GRUB_CMDLINE_LINUX="(?!hugepages=)'
    replace='GRUB_CMDLINE_LINUX="hugepages={{ nr_hugepages }}'
  become: yes

- name: set grub hugepage 1GB 
  when: hugepage_size == "1G"
  replace:
    dest=/etc/default/grub
    regexp='^GRUB_CMDLINE_LINUX="(?!default_hugepagesz=)'
    replace='GRUB_CMDLINE_LINUX="default_hugepagesz=1G hugepagesz=1G hugepages={{ nr_hugepages }}'
  become: yes

- name: update grub
  shell: update-grub
  become: yes

- name: mkdir -p /mnt/huge
  become: yes
  file: path=/mnt/huge state=directory

- name: mount hugetlbfs
  become: yes
  command: mount -t hugetlbfs nodev /mnt/huge
