---
- name: install ruby 
  become: yes
  apt: name=ruby state=present
  environment: {{ proxy_env }}

- name: install nmon
  become: yes
  apt: name=nmon state=present
  environment: {{ proxy_env }}

- name: install tmux
  become: yes
  apt: name=tmux state=present
  environment: {{ proxy_env }}

- name: put .tmux.conf
  copy: src=templates/tmux.conf dest={{ ansible_env.HOME }}/.tmux.conf mode=664
