---
- name: get rbenv
  git: repo=https://github.com/rbenv/rbenv.git
       dest={{ ansible_env.HOME }}/.rbenv

- name: configure rbenv
  command: src/configure chdir={{ ansible_env.HOME }}/.rbenv

- name: make rbenv
  command: make -C src chdir={{ ansible_env.HOME }}/.rbenv

- name: copy bash_profile
  copy: src=templates/bash_profile_rbenv dest={{ ansible_env.HOME }}/.bash_profile mode=664

- name: get ruby-build
  git: repo=https://github.com/rbenv/ruby-build.git
       dest={{ ansible_env.HOME }}/.rbenv/plugins/ruby-build
